### ISSUE TITLE
Support for NativeModules

### ISSUE THREAD

**Issue by Anahkiasen** [KodersLab/react-native-for-web#11]
Is it possible to currently mock the NativeModules so that they don't throw errors such as these:

```
Uncaught TypeError: Cannot read property 'RNVectorIconsManager' of undefined
```

I don't want them to do anything, just, be able to run the app without errors. Is there an alias I can setup for this or something? Not using it personally but one of the [packages I use uses it](https://github.com/oblador/react-native-vector-icons/blob/master/lib/create-icon-set.js#L25)

**Comment by mattiamanzati** [comment]
Thanks for reporting this! :D 
Check out the 0.1.7 version, which exports a blank object!

**Comment by Anahkiasen** [comment]
Perfect, thanks!
