### ISSUE TITLE
style prop for non rn-for-web components doesn't work with arrays

### ISSUE THREAD

**Issue by respectTheCode** [KodersLab/react-native-for-web#15]
The `style` prop is not processing arrays correctly.

`<div style={[{borderWidth: 1}, {borderColor: "blue"}]}>`

is rendered as

`<div style="0:[object Object];1:[object Object];" data-reactid=".0.0">`

**Comment by mattiamanzati** [comment]
Can you please share your code which uses View or Text?
div's are not a rn-for-web components, so they does'nt handle array styles, you have to use a View instead

**Comment by respectTheCode** [comment]
I did some more experimenting and rn-for-web components support arrays and objects and all other components only support objects.

`<View style={[{borderWidth: 1}, {borderColor: "blue"}]}>View Array</View>` - works
`<div style={[{borderWidth: 1}, {borderColor: "blue"}]}>Div Array</div>` - does not work
`<View style={{borderWidth: 1, borderColor: "blue"}}>View Object</View>` - works
`<div style={{borderWidth: 1, borderColor: "blue"}}>Div Object</div>` - works

Is there are reason not to extend `ReactElement` the way `react-style` does?

**Comment by brysgo** [comment]
@respectTheCode - My guess is because the point of this project is to make cross platform react native apps in the browser and ReactDOM is not supported by react native.

**Comment by mattiamanzati** [comment]
Yeah, that's exactly the point.
Anyway you can import 

`import browserify from 'react-native-for-web/lib/utils/style/browserify';`

and do

`<div style={browserify([{borderWidth: 1}, {borderColor: "blue"}])}></div>`

which will do the job.
As pointed in #2 the style handling will be moved to KodersLab/react-native-for-web-stylesheet, so you will be able to do that easily in the future!
