### ISSUE TITLE
*Vertical and *Horizontal style shortcuts don't work

### ISSUE THREAD

**Issue by respectTheCode** [KodersLab/react-native-for-web#16]
for example `paddingHorizontal` should be expanded to `paddingLeft` and `paddingRight`

https://facebook.github.io/react-native/docs/flexbox.html#proptypes

**Comment by mattiamanzati** [comment]
This should be already handled, maybe there's a bug?

https://github.com/KodersLab/react-native-for-web/blob/master/src/utils/style/decoupleBidirectionalProps.js

**Comment by respectTheCode** [comment]
Not a bug. I had the style on `Link` and `Link` is a `div` not a rn-for-web component.

**Comment by mattiamanzati** [comment]
As mentioned before, you may take advantage of the lib/utils/style/browserify which will take in the value of the style in rn prop and convert it into a single CSS object declaration in web! :)
