### ISSUE TITLE
TextInput  borders are not visible in chrome

### ISSUE THREAD

**Issue by chandu0101** [KodersLab/react-native-for-web#4]
Chrome : Version 45.0.2454.101 (64-bit) 

<img width="1132" alt="screen shot 2015-10-04 at 3 36 27 am" src="https://cloud.githubusercontent.com/assets/2179670/10265295/45877136-6a49-11e5-9383-b6b0ac9090dd.png">

**Comment by chandu0101** [comment]
``` css
border-top-width: 0.5px;
    border-right-width: 0.5px;
    border-bottom-width: 0.5px;
    border-left-width: 0.5px;
```

chrome not accepting values less than 1px for border-width/border-left/???-width

**Comment by mattiamanzati** [comment]
Yeah, that's reported as a Chrome known issues, as far as I know.
You can rely on box-shadow to emulate that! :)
