### ISSUE TITLE
React.Platform api ? 

### ISSUE THREAD

**Issue by chandu0101** [KodersLab/react-native-for-web#7]
does it make sense to web ?

**Comment by mattiamanzati** [comment]
It makes sense for sure, I am debating about the value of Platform.OS, maybe "browser" should be enough?

**Comment by chandu0101** [comment]
> maybe "browser" should be enough?

:+1:

**Comment by chandu0101** [comment]
@mattiamanzati  hey my library https://github.com/chandu0101/sri web module depends on react-native-for-web , currently i am using ugly hack(if(!React.Platform))  to determine if its browser , i badly need this .

I just opened a PR #9 please review it , btw few spoon feeding steps on how to run examples / update docs / publish local will be good ,especially for people like me ( new to this javascript land).

**Comment by mattiamanzati** [comment]
Yeah I'll be working on that For dure! Unfortunately until the end of the month I am a Little busy with the office, thanks For Your PR!
